name: Test

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          cache: true
          cache-dependency-path: MoEmbed.App/packages.lock.json
      - run: dotnet restore --locked-mode
      - run: dotnet build
      - name: Core Test
        working-directory: MoEmbed.Core.Tests
        run: dotnet test
      - name: Models Test
        working-directory: MoEmbed.Models.Tests
        run: dotnet test
